theme: jekyll-theme-cayman
timezone: Europe/Moscow
title: gamelton's blog
social-network-links:
  rss: true
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
permalink: /:year-:month-:day-:title/
paginate: 5
plugins:
  - jekyll-feed
